// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  graphqlEndpoint:
    "https://d6jfd3f2nzhwdnktboxspaftwu.appsync-api.us-east-2.amazonaws.com/graphql",
  region: "us-east-2",
  authenticationType: "API_KEY",
  apiKey: "da2-xfakbqgp6jglbpg7iifcyynuye"
};

export default awsmobile;
